const mongoose=require("mongoose")

const UserSchema=new mongoose.Schema({
    userName:{
        type:String,
        required:true,
        unique:true
    },
    fName:{
        type:String,
        required:true
    },
    lName:{
        type:String,
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    numberOfTestsGiven:{
        type:Number,
        default:0
    },
    totalTimeSpend:{
        type:Number,
        default:0
    },
    bestSpeed:{
        type:Number,
        default:0
    },
    averageSpeed:{
        type:Number,
        default:0
    },
    bestAccuracy:{
        type:Number,
        default:0,
        minimum:0,
        maximum:100
    },
    averageAccuracy:{
        type:Number,
        default:0,
        minimum:0,
        maximum:100
    },
    tests:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'test'
    }],
    bests:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'test'
    }],
    dateOfAccountCreated:{
        type:Date,
        default:Date.now
    },
    status:{
        type:Number,
        default:0
    }
})

const User=mongoose.model("user",UserSchema)
module.exports=User